#!/usr/bin/env bash
SCRIPTDIR="$(dirname "${0}")"
INPUT="${1}"
OUTPUTS="${HOME}/Desktop/xdcams"
if [[ ! -d "${OUTPUTS}" ]] ; then
    mkdir "${OUTPUTS}"
fi

_run_xdcam(){
    INPUT_DIR="${1}"
    "${SCRIPTDIR}/camera_cards" -m "$(basename "${1}")" -o "${OUTPUTS}" -p xp -1 "${INPUT_DIR}"
}

if [[ -d "${INPUT}" ]] ; then
    _run_xdcam "${INPUT}"
elif [[ "${INPUT##*.}" = "csv" ]] ; then
    while read INPUT_FROM_LIST ; do
        _run_xdcam "${INPUT_FROM_LIST}"
    done < <(tail -n +2 "${INPUT}" | grep -v "^," | xsv select 2)
else
    echo "Invalid input. Run like '${0} /path/to/camera/card/directory' or like '${0} /path/to/project_MEDIA_CARDS.csv'."
fi