#!/usr/bin/env bash
SCRIPTDIR="$(dirname "${0}")"
INPUT_DIR="${1}"
OUTPUTS="${HOME}/Desktop/proofsheets"
mkdir "${OUTPUTS}"
"${SCRIPTDIR}/camera_cards" -m "$(dirname "${1}")" -o "${OUTPUTS}" -p s -1 "${INPUT_DIR}"
