#!/usr/bin/env bash
SCRIPTDIR="$(dirname "${0}")"
INPUT_DIR="${1}"
OUTPUTS="${HOME}/Desktop/proofsheets"
if [[ ! -d "${OUTPUTS}" ]] ; then
    mkdir "${OUTPUTS}"
fi
"${SCRIPTDIR}/camera_cards" -m "$(basename "${1}")" -o "${OUTPUTS}" -p s -1 "${INPUT_DIR}"
